name: flutter_classwork
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  convex_bottom_bar: ^3.2.0
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^2.5.0
  carousel_slider: ^4.2.1
  font_awesome_flutter:
  flutter_custom_clippers: ^2.1.0
  google_maps_flutter: ^2.4.0
  shared_preferences: ^2.2.0
  provider:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.2
  email_validator: ^2.1.17
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_storage:
  image_picker:
  #API integration
  #get
  #flutter_staggered_grid_view
  http:
  cached_network_image:
  permission_handler:
  dio:
  internet_connection_checker:
  top_snackbar_flutter:
  scrollable_positioned_list:
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.11
  sqflite: ^2.3.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:   # to create typeadapter
  build_runner:     # to execute command in terminal and create something







  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/
  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-BoldItalic.ttf